package com.auction.service;

import com.auction.repository.UserRepository;
import jakarta.validation.constraints.*;
import lombok.Builder;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class RegistrationService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    // ───────────── REQUEST ─────────────
    public record SignupRequest(
            @NotBlank @Size(max = 120) String fullName,
            @NotBlank @Pattern(regexp = "^[0-9]{10,15}$", message = "Invalid mobile number") String mobile,
            @NotBlank @Email String email,
            @NotBlank @Size(min = 8, max = 72) String password,
            @NotBlank String confirmPassword,
            @NotBlank String companyName,
            @NotBlank String representing,
            String gstNumber,
            @NotBlank String address,
            @NotBlank String city,
            @NotBlank String state,
            @NotBlank String pincode,
            @AssertTrue(message = "You must accept the Terms of Service") boolean agreed
    ) {}

    // ───────────── RESPONSE ─────────────
    @Builder
    public record AuthResponse(Long userId, String fullName, String email, String mobile,
                               String companyName, String representing, boolean newUser) {}

    // ───────────── SIGNUP ─────────────
    @Transactional
    public AuthResponse signup(SignupRequest req) {
        if (!req.password().equals(req.confirmPassword()))
            throw new IllegalArgumentException("Passwords do not match");
        if (userRepository.existsByEmailNative(req.email()))
            throw new IllegalStateException("Email already registered");
        if (userRepository.existsByMobileNative(req.mobile()))
            throw new IllegalStateException("Mobile number already registered");

        String hash = passwordEncoder.encode(req.password());

        // 1. INSERT — returns void now
        userRepository.insertUserNative(
                req.fullName(),
                req.mobile(),
                req.email().toLowerCase(),
                hash,
                req.companyName(),
                req.representing(),
                req.gstNumber(),
                req.address(),
                req.city(),
                req.state(),
                req.pincode(),
                null);

        // 2. Fetch the id generated by Postgres
        Long id = userRepository.findIdByEmailNative(req.email());
        if (id == null) throw new IllegalStateException("Insert failed");

        // 3. Role
        userRepository.insertRoleNative(id, req.representing());

        return AuthResponse.builder()
                .userId(id)
                .fullName(req.fullName())
                .email(req.email().toLowerCase())
                .mobile(req.mobile())
                .companyName(req.companyName())
                .representing(req.representing())
                .newUser(true)
                .build();
    }

    // ───────────── GOOGLE USER ─────────────
    @Transactional
    public AuthResponse registerGoogleUser(String sub, String email, String name) {
        if (userRepository.existsByEmailNative(email))
            throw new IllegalStateException("Email already registered");

        userRepository.insertUserNative(
                name != null ? name : email,
                "",
                email.toLowerCase(),
                "",
                "",
                "",
                null, null, null, null, null,
                sub);

        Long id = userRepository.findIdByEmailNative(email);
        if (id == null) throw new IllegalStateException("Insert failed");

        userRepository.insertRoleNative(id, "");

        return AuthResponse.builder()
                .userId(id)
                .fullName(name != null ? name : email)
                .email(email.toLowerCase())
                .mobile("")
                .companyName("")
                .representing("Owner")
                .newUser(true)
                .build();
    }
}